### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by YOU54F**
hi fella,

updated packages to avoid security deps

passing travis build https://travis-ci.org/YOU54F/compat

added a package.lock but can remove

cheers

### CODE REVIEW

**Comment by YOU54F** [comment]
@jgardella Hey up chap, would you consider merging this?

**Comment by jgardella** [comment]
Hi @YOU54F,

I would, but I'm not really maintaining this tool anymore. Are you trying to use it? It seems there are now better alternatives, like [eslint-plugin-compat](https://github.com/amilajack/eslint-plugin-compat).

**Comment by YOU54F** [comment]
Hey chap, 

We are at work, and on one of my public projects

https://github.com/YOU54F/react-ts-testing-example

I also use eslint-plugin-compat but it currently doesn't check kangax tables, which is why I am using your tool.

There is also this similar tool https://github.com/kamilogorek/compat-cli but it was also not used for some time, I proposed a PR to update the deps on it.

I would be happy to help maintain this going forward, as it has already provided us useful feedback!

**Comment by jgardella** [comment]
Ok, I will merge. I wasn't aware this was being used by anyone. Happy you're finding it useful.

If you have any other PRs please do send them and I'll review.

Thanks!

**Comment by YOU54F** [comment]
Thanks mate, will do!!!

**Comment by YOU54F** [comment]
also sorry to be a pain but if you could bump the version number and do an npm release that would be ace!!!

Thanks again

**Comment by jgardella** [comment]
@YOU54F, just published 0.1.4 with your changes.

**Pull request merged**
